# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name=b'Name')),
                ('department', models.CharField(choices=[(b'Math', b'Math'), (b'English', b'English'), (b'Science', b'Science'), (b'History', b'History')], max_length=64, verbose_name=b'Department')),
                ('semester', models.CharField(choices=[(b'Fall', b'Fall'), (b'Winter', b'Winter'), (b'Spring', b'Spring'), (b'Summer', b'Summer')], max_length=64, verbose_name=b'Semester')),
                ('year', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=256, verbose_name=b'First Name')),
                ('lastname', models.CharField(max_length=256, verbose_name=b'Last Name')),
                ('email', models.EmailField(max_length=256, verbose_name=b'Email Address')),
                ('department', models.CharField(choices=[(b'Math', b'Math'), (b'English', b'English'), (b'Science', b'Science'), (b'History', b'History')], max_length=64, verbose_name=b'Department')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256, verbose_name=b'Email Address')),
                ('firstname', models.CharField(max_length=256, verbose_name=b'First Name')),
                ('lastname', models.CharField(max_length=256, verbose_name=b'Last Name')),
                ('graduation_year', models.CharField(choices=[(b'2017', b'2017'), (b'2018', b'2018'), (b'2019', b'2019'), (b'2020', b'2020')], max_length=64, verbose_name=b'Grad Year')),
                ('courses', models.ManyToManyField(blank=True, to='app.Courses', verbose_name=b'Courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Professors', verbose_name=b'Professor'),
        ),
    ]
